version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    depends_on:
      - user-db
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
    depends_on:
      - order-db
    networks:
      - microservices-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - order-service
    networks:
      - microservices-network

  user-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - microservices-network

  order-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
