version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
    networks:
      - microservices-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - order-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
